class Name_Error(Exception):
    def __init__(self):
        pass

class UrlError(Exception):
    def __intt__(self):
        pass